### ISSUE TITLE
Amiga 1000 issues

### ISSUE THREAD

**Issue by ami-commo-fan** [niklasekstrom/amiga-par-to-spi-adapter#5]
I want to report an issue running the adapter on the Amiga 1000.
The symptoms are the sdcard drive appears and disappears constantly for about 20 seconds and after is no longer accessible. All the time CPU usage is at maximum. 
When using the same adapter on amiga with standard serial port, all works well.
I was checking the connections and all the signals needed are present on A1000 par. port so I do not understand why it is not working as expected.
Could that be similar driver issue that prevented working on A3000/4000 and was fixed lately?
I tried both 2.0 and 2.1 drivers both behave the same.

**Comment by patrikaxelsson** [comment]
Got a few questions:

1. Which version of the sdbox hardware and firmware are you using?
2. Can you give some details of your A1000? Is it expanded, which kickstart and workbench is it using?

**Comment by ami-commo-fan** [comment]
It was Version 2 hardware.
I have not the specs, because friend to whom I was making the sdbox, did not send me details of his A1000 yet, I expect he is quite busy, when I have the specs I will post.

**Comment by patrikaxelsson** [comment]
Regarding A3000 fixes, you also need pullups on the parallel port lines for it to work on the A3000, see parts of discussion in this issue:
https://github.com/jbilander/sdbox/issues/18#issuecomment-1830798423

It does not sound like that is the problem in this case though, as without pullups on the A3000 it fails communicating in general - not even possible to mount a card.

Could this issue be something as simple as a bad SD socket with a super glitchy Card Detect switch, causing a storm of interrupts, overloading the Amiga and spisd.device?
